[ mlhandler ]
artifacts_dir = "./artifacts"
models_dir = "./models"
database = "./customer_data.db"
database_table = "telco"

# original test size from the model training notebook
train_test_split = 0.432

# optimized RandomForest parameters
rfc_n_estimators = 57
rfc_criterion = "gini"
rfc_max_depth = 13
rfc_min_samples_leaf = 5

[ app ]
testfiles_dir = "./testfiles"
host = "0.0.0.0"
port = 8000